[package]
name = "elysium-os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "elysium"
path = "kernel/main.rs"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
pollster = "1.0.1"
rquickjs = { version = "0.12.2", features = ["loader"] }
swc_common = "26.0.0"
swc_ecma_ast = "29.0.0"
swc_ecma_parser = "45.0.0"
swc_ecma_visit = "29.0.0"
wgpu = "30.0.1"
winit = "0.30.13"
