[package]
name = "elysium-os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "elysium"
path = "kernel/main.rs"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
cpal = "0.15"
rquickjs = { version = "0.12.2", features = ["loader", "array-buffer"] }
softbuffer = { version = "0.4.8", default-features = false, features = ["x11", "wayland"] }
swc_common = "26.0.0"
swc_ecma_ast = "29.0.0"
swc_ecma_parser = "45.0.0"
swc_ecma_visit = "29.0.0"
tiny-skia = "0.11.4"
winit = "0.30.13"
