//! `Key`: one physical key on the keyboard, independent of the active
//! keyboard layout — the same variant names and meaning as winit's
//! [`KeyCode`](winit::keyboard::KeyCode), which this module mirrors 1:1 and
//! translates into on the way in from a raw window event. Generated together
//! with the matching constants exported from
//! `kernel/runtime_modules/input.ts` so the two never drift — the
//! discriminant here is exactly the numeric id a program passes across the
//! `ely:input` boundary.

/// One physical key, identified by its position on the keyboard rather than
/// the character it produces — e.g. `KeyW` is the key in the "W" position on
/// a US layout, whatever an AZERTY keyboard prints on it. `#[repr(u16)]`
/// and explicit discriminants because the numeric value *is* the wire format
/// `ely:input`'s functions receive from JS. Most variants are only ever
/// constructed from that numeric id via [`Key::from_id`], not named directly
/// in Rust, so dead-code analysis can't see them as used — hence
/// `#[allow(dead_code)]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
#[allow(dead_code)]
pub enum Key {
    Backquote = 0,
    Backslash = 1,
    BracketLeft = 2,
    BracketRight = 3,
    Comma = 4,
    Digit0 = 5,
    Digit1 = 6,
    Digit2 = 7,
    Digit3 = 8,
    Digit4 = 9,
    Digit5 = 10,
    Digit6 = 11,
    Digit7 = 12,
    Digit8 = 13,
    Digit9 = 14,
    Equal = 15,
    IntlBackslash = 16,
    IntlRo = 17,
    IntlYen = 18,
    KeyA = 19,
    KeyB = 20,
    KeyC = 21,
    KeyD = 22,
    KeyE = 23,
    KeyF = 24,
    KeyG = 25,
    KeyH = 26,
    KeyI = 27,
    KeyJ = 28,
    KeyK = 29,
    KeyL = 30,
    KeyM = 31,
    KeyN = 32,
    KeyO = 33,
    KeyP = 34,
    KeyQ = 35,
    KeyR = 36,
    KeyS = 37,
    KeyT = 38,
    KeyU = 39,
    KeyV = 40,
    KeyW = 41,
    KeyX = 42,
    KeyY = 43,
    KeyZ = 44,
    Minus = 45,
    Period = 46,
    Quote = 47,
    Semicolon = 48,
    Slash = 49,
    AltLeft = 50,
    AltRight = 51,
    Backspace = 52,
    CapsLock = 53,
    ContextMenu = 54,
    ControlLeft = 55,
    ControlRight = 56,
    Enter = 57,
    SuperLeft = 58,
    SuperRight = 59,
    ShiftLeft = 60,
    ShiftRight = 61,
    Space = 62,
    Tab = 63,
    Convert = 64,
    KanaMode = 65,
    Lang1 = 66,
    Lang2 = 67,
    Lang3 = 68,
    Lang4 = 69,
    Lang5 = 70,
    NonConvert = 71,
    Delete = 72,
    End = 73,
    Help = 74,
    Home = 75,
    Insert = 76,
    PageDown = 77,
    PageUp = 78,
    ArrowDown = 79,
    ArrowLeft = 80,
    ArrowRight = 81,
    ArrowUp = 82,
    NumLock = 83,
    Numpad0 = 84,
    Numpad1 = 85,
    Numpad2 = 86,
    Numpad3 = 87,
    Numpad4 = 88,
    Numpad5 = 89,
    Numpad6 = 90,
    Numpad7 = 91,
    Numpad8 = 92,
    Numpad9 = 93,
    NumpadAdd = 94,
    NumpadBackspace = 95,
    NumpadClear = 96,
    NumpadClearEntry = 97,
    NumpadComma = 98,
    NumpadDecimal = 99,
    NumpadDivide = 100,
    NumpadEnter = 101,
    NumpadEqual = 102,
    NumpadHash = 103,
    NumpadMemoryAdd = 104,
    NumpadMemoryClear = 105,
    NumpadMemoryRecall = 106,
    NumpadMemoryStore = 107,
    NumpadMemorySubtract = 108,
    NumpadMultiply = 109,
    NumpadParenLeft = 110,
    NumpadParenRight = 111,
    NumpadStar = 112,
    NumpadSubtract = 113,
    Escape = 114,
    Fn = 115,
    FnLock = 116,
    PrintScreen = 117,
    ScrollLock = 118,
    Pause = 119,
    BrowserBack = 120,
    BrowserFavorites = 121,
    BrowserForward = 122,
    BrowserHome = 123,
    BrowserRefresh = 124,
    BrowserSearch = 125,
    BrowserStop = 126,
    Eject = 127,
    LaunchApp1 = 128,
    LaunchApp2 = 129,
    LaunchMail = 130,
    MediaPlayPause = 131,
    MediaSelect = 132,
    MediaStop = 133,
    MediaTrackNext = 134,
    MediaTrackPrevious = 135,
    Power = 136,
    Sleep = 137,
    AudioVolumeDown = 138,
    AudioVolumeMute = 139,
    AudioVolumeUp = 140,
    WakeUp = 141,
    Meta = 142,
    Hyper = 143,
    Turbo = 144,
    Abort = 145,
    Resume = 146,
    Suspend = 147,
    Again = 148,
    Copy = 149,
    Cut = 150,
    Find = 151,
    Open = 152,
    Paste = 153,
    Props = 154,
    Select = 155,
    Undo = 156,
    Hiragana = 157,
    Katakana = 158,
    F1 = 159,
    F2 = 160,
    F3 = 161,
    F4 = 162,
    F5 = 163,
    F6 = 164,
    F7 = 165,
    F8 = 166,
    F9 = 167,
    F10 = 168,
    F11 = 169,
    F12 = 170,
    F13 = 171,
    F14 = 172,
    F15 = 173,
    F16 = 174,
    F17 = 175,
    F18 = 176,
    F19 = 177,
    F20 = 178,
    F21 = 179,
    F22 = 180,
    F23 = 181,
    F24 = 182,
    F25 = 183,
    F26 = 184,
    F27 = 185,
    F28 = 186,
    F29 = 187,
    F30 = 188,
    F31 = 189,
    F32 = 190,
    F33 = 191,
    F34 = 192,
    F35 = 193,
}

impl Key {
    /// Number of variants — valid discriminants are exactly `0..COUNT`.
    pub const COUNT: usize = 194;

    /// Converts a numeric id crossing the `ely:input` boundary from JS back
    /// into a `Key`, or `None` if it's out of range.
    pub fn from_id(id: u16) -> Option<Key> {
        if (id as usize) < Self::COUNT {
            // SAFETY: `Key` is `#[repr(u16)]` with dense discriminants
            // `0..COUNT`, just checked `id` falls in that range.
            Some(unsafe { std::mem::transmute::<u16, Key>(id) })
        } else {
            None
        }
    }

    /// Translates a winit physical key code into the matching `Key`, or
    /// `None` for a code this enum doesn't have an entry for (`KeyCode` is
    /// `#[non_exhaustive]`, so winit can add variants this match won't yet
    /// know about).
    pub fn from_key_code(code: winit::keyboard::KeyCode) -> Option<Key> {
        match code {
            winit::keyboard::KeyCode::Backquote => Some(Key::Backquote),
            winit::keyboard::KeyCode::Backslash => Some(Key::Backslash),
            winit::keyboard::KeyCode::BracketLeft => Some(Key::BracketLeft),
            winit::keyboard::KeyCode::BracketRight => Some(Key::BracketRight),
            winit::keyboard::KeyCode::Comma => Some(Key::Comma),
            winit::keyboard::KeyCode::Digit0 => Some(Key::Digit0),
            winit::keyboard::KeyCode::Digit1 => Some(Key::Digit1),
            winit::keyboard::KeyCode::Digit2 => Some(Key::Digit2),
            winit::keyboard::KeyCode::Digit3 => Some(Key::Digit3),
            winit::keyboard::KeyCode::Digit4 => Some(Key::Digit4),
            winit::keyboard::KeyCode::Digit5 => Some(Key::Digit5),
            winit::keyboard::KeyCode::Digit6 => Some(Key::Digit6),
            winit::keyboard::KeyCode::Digit7 => Some(Key::Digit7),
            winit::keyboard::KeyCode::Digit8 => Some(Key::Digit8),
            winit::keyboard::KeyCode::Digit9 => Some(Key::Digit9),
            winit::keyboard::KeyCode::Equal => Some(Key::Equal),
            winit::keyboard::KeyCode::IntlBackslash => Some(Key::IntlBackslash),
            winit::keyboard::KeyCode::IntlRo => Some(Key::IntlRo),
            winit::keyboard::KeyCode::IntlYen => Some(Key::IntlYen),
            winit::keyboard::KeyCode::KeyA => Some(Key::KeyA),
            winit::keyboard::KeyCode::KeyB => Some(Key::KeyB),
            winit::keyboard::KeyCode::KeyC => Some(Key::KeyC),
            winit::keyboard::KeyCode::KeyD => Some(Key::KeyD),
            winit::keyboard::KeyCode::KeyE => Some(Key::KeyE),
            winit::keyboard::KeyCode::KeyF => Some(Key::KeyF),
            winit::keyboard::KeyCode::KeyG => Some(Key::KeyG),
            winit::keyboard::KeyCode::KeyH => Some(Key::KeyH),
            winit::keyboard::KeyCode::KeyI => Some(Key::KeyI),
            winit::keyboard::KeyCode::KeyJ => Some(Key::KeyJ),
            winit::keyboard::KeyCode::KeyK => Some(Key::KeyK),
            winit::keyboard::KeyCode::KeyL => Some(Key::KeyL),
            winit::keyboard::KeyCode::KeyM => Some(Key::KeyM),
            winit::keyboard::KeyCode::KeyN => Some(Key::KeyN),
            winit::keyboard::KeyCode::KeyO => Some(Key::KeyO),
            winit::keyboard::KeyCode::KeyP => Some(Key::KeyP),
            winit::keyboard::KeyCode::KeyQ => Some(Key::KeyQ),
            winit::keyboard::KeyCode::KeyR => Some(Key::KeyR),
            winit::keyboard::KeyCode::KeyS => Some(Key::KeyS),
            winit::keyboard::KeyCode::KeyT => Some(Key::KeyT),
            winit::keyboard::KeyCode::KeyU => Some(Key::KeyU),
            winit::keyboard::KeyCode::KeyV => Some(Key::KeyV),
            winit::keyboard::KeyCode::KeyW => Some(Key::KeyW),
            winit::keyboard::KeyCode::KeyX => Some(Key::KeyX),
            winit::keyboard::KeyCode::KeyY => Some(Key::KeyY),
            winit::keyboard::KeyCode::KeyZ => Some(Key::KeyZ),
            winit::keyboard::KeyCode::Minus => Some(Key::Minus),
            winit::keyboard::KeyCode::Period => Some(Key::Period),
            winit::keyboard::KeyCode::Quote => Some(Key::Quote),
            winit::keyboard::KeyCode::Semicolon => Some(Key::Semicolon),
            winit::keyboard::KeyCode::Slash => Some(Key::Slash),
            winit::keyboard::KeyCode::AltLeft => Some(Key::AltLeft),
            winit::keyboard::KeyCode::AltRight => Some(Key::AltRight),
            winit::keyboard::KeyCode::Backspace => Some(Key::Backspace),
            winit::keyboard::KeyCode::CapsLock => Some(Key::CapsLock),
            winit::keyboard::KeyCode::ContextMenu => Some(Key::ContextMenu),
            winit::keyboard::KeyCode::ControlLeft => Some(Key::ControlLeft),
            winit::keyboard::KeyCode::ControlRight => Some(Key::ControlRight),
            winit::keyboard::KeyCode::Enter => Some(Key::Enter),
            winit::keyboard::KeyCode::SuperLeft => Some(Key::SuperLeft),
            winit::keyboard::KeyCode::SuperRight => Some(Key::SuperRight),
            winit::keyboard::KeyCode::ShiftLeft => Some(Key::ShiftLeft),
            winit::keyboard::KeyCode::ShiftRight => Some(Key::ShiftRight),
            winit::keyboard::KeyCode::Space => Some(Key::Space),
            winit::keyboard::KeyCode::Tab => Some(Key::Tab),
            winit::keyboard::KeyCode::Convert => Some(Key::Convert),
            winit::keyboard::KeyCode::KanaMode => Some(Key::KanaMode),
            winit::keyboard::KeyCode::Lang1 => Some(Key::Lang1),
            winit::keyboard::KeyCode::Lang2 => Some(Key::Lang2),
            winit::keyboard::KeyCode::Lang3 => Some(Key::Lang3),
            winit::keyboard::KeyCode::Lang4 => Some(Key::Lang4),
            winit::keyboard::KeyCode::Lang5 => Some(Key::Lang5),
            winit::keyboard::KeyCode::NonConvert => Some(Key::NonConvert),
            winit::keyboard::KeyCode::Delete => Some(Key::Delete),
            winit::keyboard::KeyCode::End => Some(Key::End),
            winit::keyboard::KeyCode::Help => Some(Key::Help),
            winit::keyboard::KeyCode::Home => Some(Key::Home),
            winit::keyboard::KeyCode::Insert => Some(Key::Insert),
            winit::keyboard::KeyCode::PageDown => Some(Key::PageDown),
            winit::keyboard::KeyCode::PageUp => Some(Key::PageUp),
            winit::keyboard::KeyCode::ArrowDown => Some(Key::ArrowDown),
            winit::keyboard::KeyCode::ArrowLeft => Some(Key::ArrowLeft),
            winit::keyboard::KeyCode::ArrowRight => Some(Key::ArrowRight),
            winit::keyboard::KeyCode::ArrowUp => Some(Key::ArrowUp),
            winit::keyboard::KeyCode::NumLock => Some(Key::NumLock),
            winit::keyboard::KeyCode::Numpad0 => Some(Key::Numpad0),
            winit::keyboard::KeyCode::Numpad1 => Some(Key::Numpad1),
            winit::keyboard::KeyCode::Numpad2 => Some(Key::Numpad2),
            winit::keyboard::KeyCode::Numpad3 => Some(Key::Numpad3),
            winit::keyboard::KeyCode::Numpad4 => Some(Key::Numpad4),
            winit::keyboard::KeyCode::Numpad5 => Some(Key::Numpad5),
            winit::keyboard::KeyCode::Numpad6 => Some(Key::Numpad6),
            winit::keyboard::KeyCode::Numpad7 => Some(Key::Numpad7),
            winit::keyboard::KeyCode::Numpad8 => Some(Key::Numpad8),
            winit::keyboard::KeyCode::Numpad9 => Some(Key::Numpad9),
            winit::keyboard::KeyCode::NumpadAdd => Some(Key::NumpadAdd),
            winit::keyboard::KeyCode::NumpadBackspace => Some(Key::NumpadBackspace),
            winit::keyboard::KeyCode::NumpadClear => Some(Key::NumpadClear),
            winit::keyboard::KeyCode::NumpadClearEntry => Some(Key::NumpadClearEntry),
            winit::keyboard::KeyCode::NumpadComma => Some(Key::NumpadComma),
            winit::keyboard::KeyCode::NumpadDecimal => Some(Key::NumpadDecimal),
            winit::keyboard::KeyCode::NumpadDivide => Some(Key::NumpadDivide),
            winit::keyboard::KeyCode::NumpadEnter => Some(Key::NumpadEnter),
            winit::keyboard::KeyCode::NumpadEqual => Some(Key::NumpadEqual),
            winit::keyboard::KeyCode::NumpadHash => Some(Key::NumpadHash),
            winit::keyboard::KeyCode::NumpadMemoryAdd => Some(Key::NumpadMemoryAdd),
            winit::keyboard::KeyCode::NumpadMemoryClear => Some(Key::NumpadMemoryClear),
            winit::keyboard::KeyCode::NumpadMemoryRecall => Some(Key::NumpadMemoryRecall),
            winit::keyboard::KeyCode::NumpadMemoryStore => Some(Key::NumpadMemoryStore),
            winit::keyboard::KeyCode::NumpadMemorySubtract => Some(Key::NumpadMemorySubtract),
            winit::keyboard::KeyCode::NumpadMultiply => Some(Key::NumpadMultiply),
            winit::keyboard::KeyCode::NumpadParenLeft => Some(Key::NumpadParenLeft),
            winit::keyboard::KeyCode::NumpadParenRight => Some(Key::NumpadParenRight),
            winit::keyboard::KeyCode::NumpadStar => Some(Key::NumpadStar),
            winit::keyboard::KeyCode::NumpadSubtract => Some(Key::NumpadSubtract),
            winit::keyboard::KeyCode::Escape => Some(Key::Escape),
            winit::keyboard::KeyCode::Fn => Some(Key::Fn),
            winit::keyboard::KeyCode::FnLock => Some(Key::FnLock),
            winit::keyboard::KeyCode::PrintScreen => Some(Key::PrintScreen),
            winit::keyboard::KeyCode::ScrollLock => Some(Key::ScrollLock),
            winit::keyboard::KeyCode::Pause => Some(Key::Pause),
            winit::keyboard::KeyCode::BrowserBack => Some(Key::BrowserBack),
            winit::keyboard::KeyCode::BrowserFavorites => Some(Key::BrowserFavorites),
            winit::keyboard::KeyCode::BrowserForward => Some(Key::BrowserForward),
            winit::keyboard::KeyCode::BrowserHome => Some(Key::BrowserHome),
            winit::keyboard::KeyCode::BrowserRefresh => Some(Key::BrowserRefresh),
            winit::keyboard::KeyCode::BrowserSearch => Some(Key::BrowserSearch),
            winit::keyboard::KeyCode::BrowserStop => Some(Key::BrowserStop),
            winit::keyboard::KeyCode::Eject => Some(Key::Eject),
            winit::keyboard::KeyCode::LaunchApp1 => Some(Key::LaunchApp1),
            winit::keyboard::KeyCode::LaunchApp2 => Some(Key::LaunchApp2),
            winit::keyboard::KeyCode::LaunchMail => Some(Key::LaunchMail),
            winit::keyboard::KeyCode::MediaPlayPause => Some(Key::MediaPlayPause),
            winit::keyboard::KeyCode::MediaSelect => Some(Key::MediaSelect),
            winit::keyboard::KeyCode::MediaStop => Some(Key::MediaStop),
            winit::keyboard::KeyCode::MediaTrackNext => Some(Key::MediaTrackNext),
            winit::keyboard::KeyCode::MediaTrackPrevious => Some(Key::MediaTrackPrevious),
            winit::keyboard::KeyCode::Power => Some(Key::Power),
            winit::keyboard::KeyCode::Sleep => Some(Key::Sleep),
            winit::keyboard::KeyCode::AudioVolumeDown => Some(Key::AudioVolumeDown),
            winit::keyboard::KeyCode::AudioVolumeMute => Some(Key::AudioVolumeMute),
            winit::keyboard::KeyCode::AudioVolumeUp => Some(Key::AudioVolumeUp),
            winit::keyboard::KeyCode::WakeUp => Some(Key::WakeUp),
            winit::keyboard::KeyCode::Meta => Some(Key::Meta),
            winit::keyboard::KeyCode::Hyper => Some(Key::Hyper),
            winit::keyboard::KeyCode::Turbo => Some(Key::Turbo),
            winit::keyboard::KeyCode::Abort => Some(Key::Abort),
            winit::keyboard::KeyCode::Resume => Some(Key::Resume),
            winit::keyboard::KeyCode::Suspend => Some(Key::Suspend),
            winit::keyboard::KeyCode::Again => Some(Key::Again),
            winit::keyboard::KeyCode::Copy => Some(Key::Copy),
            winit::keyboard::KeyCode::Cut => Some(Key::Cut),
            winit::keyboard::KeyCode::Find => Some(Key::Find),
            winit::keyboard::KeyCode::Open => Some(Key::Open),
            winit::keyboard::KeyCode::Paste => Some(Key::Paste),
            winit::keyboard::KeyCode::Props => Some(Key::Props),
            winit::keyboard::KeyCode::Select => Some(Key::Select),
            winit::keyboard::KeyCode::Undo => Some(Key::Undo),
            winit::keyboard::KeyCode::Hiragana => Some(Key::Hiragana),
            winit::keyboard::KeyCode::Katakana => Some(Key::Katakana),
            winit::keyboard::KeyCode::F1 => Some(Key::F1),
            winit::keyboard::KeyCode::F2 => Some(Key::F2),
            winit::keyboard::KeyCode::F3 => Some(Key::F3),
            winit::keyboard::KeyCode::F4 => Some(Key::F4),
            winit::keyboard::KeyCode::F5 => Some(Key::F5),
            winit::keyboard::KeyCode::F6 => Some(Key::F6),
            winit::keyboard::KeyCode::F7 => Some(Key::F7),
            winit::keyboard::KeyCode::F8 => Some(Key::F8),
            winit::keyboard::KeyCode::F9 => Some(Key::F9),
            winit::keyboard::KeyCode::F10 => Some(Key::F10),
            winit::keyboard::KeyCode::F11 => Some(Key::F11),
            winit::keyboard::KeyCode::F12 => Some(Key::F12),
            winit::keyboard::KeyCode::F13 => Some(Key::F13),
            winit::keyboard::KeyCode::F14 => Some(Key::F14),
            winit::keyboard::KeyCode::F15 => Some(Key::F15),
            winit::keyboard::KeyCode::F16 => Some(Key::F16),
            winit::keyboard::KeyCode::F17 => Some(Key::F17),
            winit::keyboard::KeyCode::F18 => Some(Key::F18),
            winit::keyboard::KeyCode::F19 => Some(Key::F19),
            winit::keyboard::KeyCode::F20 => Some(Key::F20),
            winit::keyboard::KeyCode::F21 => Some(Key::F21),
            winit::keyboard::KeyCode::F22 => Some(Key::F22),
            winit::keyboard::KeyCode::F23 => Some(Key::F23),
            winit::keyboard::KeyCode::F24 => Some(Key::F24),
            winit::keyboard::KeyCode::F25 => Some(Key::F25),
            winit::keyboard::KeyCode::F26 => Some(Key::F26),
            winit::keyboard::KeyCode::F27 => Some(Key::F27),
            winit::keyboard::KeyCode::F28 => Some(Key::F28),
            winit::keyboard::KeyCode::F29 => Some(Key::F29),
            winit::keyboard::KeyCode::F30 => Some(Key::F30),
            winit::keyboard::KeyCode::F31 => Some(Key::F31),
            winit::keyboard::KeyCode::F32 => Some(Key::F32),
            winit::keyboard::KeyCode::F33 => Some(Key::F33),
            winit::keyboard::KeyCode::F34 => Some(Key::F34),
            winit::keyboard::KeyCode::F35 => Some(Key::F35),
            _ => None,
        }
    }
}
